names:
  - Mibzle Gork
  - Tilda Fizzlepot
  - Brum the Quiet
  - Zarnak Doomwhisper
  - Pip Thimbletoe
  - Glimmer Fernwhistle
  - Snorgus the Flatulent
  - Ellie of the Endless Tea

jobs:
  - wand polisher
  - dragon dentist
  - potion tester
  - bard critic
  - sock merchant
  - wandering poet
  - goblin negotiator
  - beholder stylist

quirks:
  - only speaks in rhymes
  - thinks they're invisible
  - collects spoons
  - scared of butterflies
  - believes they're a potato
  - hums constantly
  - obsessed with ducks
  - always narrating their actions

moods:
  - mysteriously excited
  - deeply confused
  - overly confident
  - melancholic but hopeful
  - suspiciously friendly
  - dramatically bored
  - quietly panicked
  - whimsically angry

species:
  - Human
  - Elf
  - Dwarf
  - Halfling
  - Gnome
  - Half-Orc
  - Dragonborn
  - Tiefling
  - Goblin
  - Fairy

alignments:
  - Lawful Good
  - Neutral Good
  - Chaotic Good
  - Lawful Neutral
  - True Neutral
  - Chaotic Neutral
  - Lawful Evil
  - Neutral Evil
  - Chaotic Evil
